### PR TITLE
Added react-router v6, added links for collectionpage

### PR DESCRIPTION
**Pull request by lape15**
PR is still a WIP @onyi2020 
Gonna push the an update soon

### CODE REVIEW

**Comment by lape15** [comment]
Ready for review @onyi2020 
I guess it is time for us to add an authentication flow to checkout.
I think we should consider firebase for that, what do you think?

**Comment by onyi2020** [comment]
> Ready for review @onyi2020 I guess it is time for us to add an authentication flow to checkout. I think we should consider firebase for that, what do you think?

All right. Not a bad idea, but maybe we should finish basic functionality first.

**Comment by onyi2020** [comment]
> Ready for review @onyi2020 I guess it is time for us to add an authentication flow to checkout. I think we should consider firebase for that, what do you think?

All right. Not a bad idea, but maybe we should finish basic functionality first.

**Comment by onyi2020** [comment]
Omo!.. you are boss o. Been thinking of how to implement what you did here. It looks good to me though but I will check into the branch so that I will fully understand

**Pull request merged**
